# Disasters & Emergencies
The Disasters & Emergencies (D&E) Resilience Index is based on the [Sendai Framework](https://www.preventionweb.net/files/43291_sendaiframeworkfordrren.pdf), developed by the United Nations Office for Disaster Risk Reduction. The Framework is is an internationally agreed-upon approach to protecting development gains from risks of disaster. It identifies the following dimensions of disaster risk: vulnerability, capacity, exposure to hazards, and characteristics of hazards; we operationalise this into a model of disaster risk based on **individual/household vulnerability**, **community/system capacity**, and **exposure to hazards**.

The current version of the D&E Resilience Index maps vulnerability, capacity, and hazards for **Local Authorities** in the UK.

## Individual and houshold vulnerability to disasters
Vulnerability is defined, inspired by the Hyogo Framework for Action as used in the Sendai Framework, as the personal and situational characteristics that increase an individual's or household's susceptibility to the negative impacts of hazards.

Our current, 'generic' approach to modelling vulnerability across a range of hazards is comprised of the following indicators:

- Older age
- Living alone
- Living with disabilities
- Housing quality
- Access to key services
- Digital exclusion

## Community and system capacity to prepare/respond/recover
The Sendai Framework is agnostic on defining 'capacity'. We operationalise a definition of capacity using the following indicators:

- Local Authority spending power (as a proxy for service/support availability and quality)
- The presence of community assets
- Community engagement and civic participation
- Fire and Rescue Service response times

## Hazards
The D&E Resilience Index currently includes data for three kinds of hazard:

- Flooding (both flood risks and historical flood incidents)
- Heatwaves (risks)
- Dwelling fires (historical incidents)

# Limitations, considerations, and future developments
The determinants of vulnerability are complex and intertwined; they change over a person's life. Vulnerabilities may emerge, change, compound and persist over long periods, passing from generation to generation - and widening inequalities. Our model of vulnerability is cross-sectional rather than longitudinal, so cannot account for such changes. However, we will update the underlying indicators of vulnerability on an annual basis so that the Index has the most updated cross-sectional view of vulnerability and capacity.

Intersectional vulnerabilities should be discussed at all times (i.e., taking into account people's overlapping identities and experiences in order to understand the complexity of discrimination and privileges they face).

The current version of the D&E Resilience Index uses a single model of vulnerability and a single model of capacity, regardless of hazard. For future versions, we are exploring how best to model vulnerability to different types of hazard, potentially ending up with one vulnerability model for flooding, another vulnerability model for heatwaves, etc. We will do so only for hazards with strong spatial predictability. This means future versions may not include a map for dwelling fires; instead, we would produce an analysis of vulnerable cohorts at risk of experiencing dwelling fires. (How we model community/system capacity is likely to remain constant across different types of hazard.)

The future version(s) will map vulnerability within Middle Layer Super Output Areas (MSOAs) in England/Wales, Intermediate Zones in Scotland, and Super Output Areas in Scotland. These are small areas containing roughly 5,000 - 15,000 people. Capacity is likely to remain at Local Authority-level, although we will explore methods for modelling capacity within MSOAs.
